const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',home:'<path d="m3 10 9-7 9 7v11h-7v-7h-4v7H3Z"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-3a8 6 0 0 1 16 0v3"/>',check:'<path d="m5 12 5 5L20 7"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.bag}</svg>`;const money=n=>Number(n).toLocaleString('ru-RU');const pfind=id=>PRODUCTS.find(p=>p.id===id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let mode=new URLSearchParams(location.search).get('view')==='site'?'site':'mini', page='home',category='Все',search='',sort='popular',cart={},saved=[],lastOrder=null,returnFocus=null;
function paintIcons(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon))}
function setMode(m){closeModal();mode=m;page='home';document.title=m==='site'?'KANISHKA — авторские изделия из Узбекистана':'KANISHKA — Mini App · концепт ATLAS';document.body.className=m+'-mode';document.getElementById('miniMode').classList.toggle('active',m==='mini');document.getElementById('siteMode').classList.toggle('active',m==='site');const u=new URL(location.href);u.searchParams.set('view',m);history.replaceState(null,'',u);render();window.scrollTo(0,0)}
function navigate(p){page=p;closeModal();render();window.scrollTo({top:0,behavior:'smooth'})}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function add(id){if(!pfind(id))throw Error('Неизвестный товар');if(!Number.isFinite(pfind(id).price)){detail(id);return;}cart[id]=Math.min(20,(cart[id]||0)+1);updateCount();toast('Товар добавлен в корзину')}
function updateCount(){document.getElementById('count').textContent=Object.values(cart).reduce((a,b)=>a+b,0)||''}
function favorite(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];document.querySelectorAll(`[data-wish="${id}"]`).forEach(e=>{e.classList.toggle('on',saved.includes(id));e.setAttribute('aria-pressed',saved.includes(id))});if(page==='saved')render();toast(saved.includes(id)?'Сохранено в избранное':'Удалено из избранного')}
function card(p){return `<article class="product"><div class="photo"><button class="open-product" onclick="detail('${p.id}')" aria-label="Открыть ${p.name}"><img src="${p.img}" alt="${p.type} KANISHKA ${p.name}" loading="lazy" width="613" height="920"></button><button class="wish ${saved.includes(p.id)?'on':''}" data-wish="${p.id}" aria-label="В избранное ${p.name}" aria-pressed="${saved.includes(p.id)}" onclick="favorite('${p.id}')">${svg('heart')}</button></div><div class="product-info"><small>${p.type}</small><h3><button style="padding:0;font:inherit" onclick="detail('${p.id}')">${p.name}</button></h3><div class="price">${Number.isFinite(p.price)?money(p.price)+' <small>сум</small>':'<small>Цена по запросу</small>'}</div><button class="add-small" onclick="${Number.isFinite(p.price)?'add':'detail'}('${p.id}')" aria-label="${Number.isFinite(p.price)?'Добавить в корзину':'Подробнее'} ${p.name}">${Number.isFinite(p.price)?'+':'·'}</button></div></article>`}
const cats=['Все',...new Set(PRODUCTS.map(p=>p.category))];
function collection(c,img){return `<button class="collection ${category===c?'active':''}" onclick="category='${c}';navigate('catalog')"><span class="circle"><img src="${img}" alt=""></span>${c==='Все'?'Вся коллекция':c}</button>`}
function home(){return `${mode==='site'?`<section class="hero"><div class="hero-copy"><div class="eyebrow">KANISHKA / MADE IN UZBEKISTAN</div><h1>Вещи<br>с характером.<br>На каждый день.</h1><p>Натуральная кожа. Ручная работа.<br>Авторские изделия из Ташкента.</p><button class="primary" onclick="category='Все';navigate('catalog')">Смотреть коллекцию</button></div><img src="assets/bulbul.jpg" alt="Кожаная сумка KANISHKA BULBUL" fetchpriority="high"></section>`:`<div class="intro"><div><div class="eyebrow">НАТУРАЛЬНО. НАДОЛГО.</div><h1>Кожа с характером</h1></div><p>Ручная работа.<br>Сделано в Узбекистане.</p></div>`}<div class="collections">${cats.map(c=>collection(c,c==='Все'?'assets/bulbul.jpg':PRODUCTS.find(p=>p.category===c).img)).join('')}</div><div class="section-head"><h2>В фокусе</h2><button class="textlink" onclick="category='Все';navigate('catalog')">Все изделия</button></div><div class="grid">${PRODUCTS.slice(0,8).map(card).join('')}</div><section class="story"><img src="assets/chopon.jpg" alt="Шоппер KANISHKA CHOPON" loading="lazy"><div><div class="eyebrow">ГОРОД. ДЕЛА. ВЫХОДНЫЕ.</div><h2>Ваш ритм.<br>Ваш характер.</h2><p>Сумки и аксессуары, которые становятся частью вашей истории.</p><button class="pill" onclick="category='Сумки';navigate('catalog')">Выбрать сумку</button></div></section>`}
function filtered(){let p=PRODUCTS.filter(p=>(category==='Все'||p.category===category)&&`${p.name} ${p.type} ${p.category}`.toLowerCase().includes(search.toLowerCase()));if(sort==='low')p.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(sort==='high')p.sort((a,b)=>(b.price??-Infinity)-(a.price??-Infinity));return p}
function results(){const p=filtered();return p.length?`<div class="grid">${p.map(card).join('')}</div>`:`<div class="empty"><h2>Ничего не найдено</h2><p>Попробуйте другое название или категорию.</p><button class="secondary" onclick="search='';category='Все';render()">Сбросить поиск</button></div>`}
function catalog(){return `<div class="eyebrow">КОЛЛЕКЦИЯ KANISHKA</div><h1>Каталог <small style="font:14px Arial;color:var(--muted)">${PRODUCTS.length} изделий</small></h1><div class="filters"><div class="searchbox"><input id="search" type="search" aria-label="Поиск по каталогу" placeholder="Найти своё изделие" value="${esc(search)}" oninput="search=this.value;document.getElementById('results').innerHTML=results()"></div><select aria-label="Сортировка" onchange="sort=this.value;document.getElementById('results').innerHTML=results()"><option value="popular" ${sort==='popular'?'selected':''}>Подборка</option><option value="low" ${sort==='low'?'selected':''}>Сначала дешевле</option><option value="high" ${sort==='high'?'selected':''}>Сначала дороже</option></select></div><div class="chips">${cats.map(c=>`<button class="${category===c?'active':''}" onclick="category='${c}';render()">${c}</button>`).join('')}</div><div id="results">${results()}</div>`}
function empty(type,title,text){return `<div class="empty">${svg(type)}<h2>${title}</h2><p>${text}</p><button class="primary" onclick="category='Все';navigate('catalog')">Открыть каталог</button></div>`}
function cartTotal(){return Object.entries(cart).reduce((s,[id,n])=>s+pfind(id).price*n,0)}
function changeQty(id,delta){cart[id]=Math.max(0,Math.min(20,(cart[id]||0)+delta));if(!cart[id])delete cart[id];render()}
function cartView(){if(!Object.keys(cart).length)return empty('bag','Корзина пока пуста','Начните с изделия, которое вам понравилось.');return `<div class="eyebrow">ВАШ ВЫБОР</div><h1>Корзина</h1><div class="cart-layout"><div>${Object.entries(cart).map(([id,n])=>{let p=pfind(id);return `<div class="cart-row"><button style="padding:0" onclick="detail('${id}')"><img src="${p.img}" alt="${p.name}"></button><div class="info"><small class="text-muted">${p.type}</small><h3>${p.name}</h3><div>${money(p.price*n)} сум</div><div class="qty"><button aria-label="Уменьшить количество ${p.name}" onclick="changeQty('${id}',-1)">−</button><span>${n}</span><button aria-label="Увеличить количество ${p.name}" onclick="changeQty('${id}',1)" ${n>=20?'disabled':''}>+</button><button style="border:0;width:auto" class="remove" onclick="delete cart['${id}'];render()">Удалить</button></div></div></div>`}).join('')}</div><aside class="summary"><h2>Ваш заказ</h2><div class="summary-line"><span>Изделия</span><span>${money(cartTotal())} сум</span></div><div class="summary-line text-muted"><span>Доставка</span><span>Уточняется</span></div><div class="summary-line total"><span>Подытог</span><span>${money(cartTotal())} сум</span></div><button class="primary full" onclick="navigate('checkout')">Перейти к оформлению</button><p class="notice">Демонстрационный заказ. Деньги не списываются.</p></aside></div>`}
function checkout(){if(!Object.keys(cart).length)return cartView();return `<button class="textlink" onclick="navigate('cart')">Вернуться в корзину</button><form class="form" onsubmit="completeOrder(event)"><div class="eyebrow">ДЕМО · БЕЗ ОТПРАВКИ ДАННЫХ</div><h1>Оформление</h1><p class="notice">Проверьте сценарий на тестовых данных. Заказ не поступит в магазин.</p><label>Имя<input name="name" required maxlength="60" value="Тестовый покупатель" autocomplete="off"></label><label>Телефон<input name="phone" required type="tel" pattern="[+]998[0-9 ]{9,15}" value="+998 90 000 00 00" autocomplete="off"></label><label>Как получить<select name="delivery" onchange="document.getElementById('addressBlock').hidden=this.value==='pickup'"><option value="pickup">Самовывоз · Шота Руставели, 39</option><option value="courier">Доставка по Ташкенту</option></select></label><label id="addressBlock" hidden>Адрес доставки<input name="address" value="Тестовый адрес" maxlength="180" autocomplete="off"></label><label>Оплата<select name="payment"><option>При получении · демо</option><option>Payme · демонстрация</option><option>Click · демонстрация</option></select></label><div class="summary-line total"><span>Товары</span><strong>${money(cartTotal())} сум</strong></div><p class="notice">Стоимость доставки и наличие подтверждает менеджер. Платёжные сервисы в макете не подключены.</p><button type="submit" class="primary full">Завершить демо-заказ</button></form>`}
function completeOrder(e){e.preventDefault();lastOrder={number:'DEMO-001',total:cartTotal(),items:Object.entries(cart).map(([id,qty])=>({id,qty})),status:'Демонстрация завершена'};cart={};page='success';render();window.scrollTo(0,0)}
function profile(){return `<div class="eyebrow">ЛИЧНЫЙ КАБИНЕТ</div><h1>Здравствуйте</h1><div class="profile-card"><h3>Гость · демо-профиль</h3><p>В готовом Mini App профиль будет открываться через Telegram.</p><button class="textlink" onclick="navigate('saved')">Избранное (${saved.length})</button></div><div class="profile-card"><h2>Ваши заказы</h2>${lastOrder?`<p>${lastOrder.number} · ${money(lastOrder.total)} сум</p><p>${lastOrder.status}. В магазин не отправлен.</p>`:'<p>Здесь появится ваш демонстрационный заказ.</p>'}</div><div class="profile-card"><h2>Магазины в Ташкенте</h2><p>Шота Руставели, 39<br>Афросиаб, 39<br>Оккурган, 21</p><p class="notice">Адреса из публикаций бренда. Режим работы уточняйте перед визитом.</p><a class="textlink" href="https://t.me/kanishka_dsgn" target="_blank" rel="noopener">Канал KANISHKA</a></div>`}
function render(){if(mode==='site'){document.getElementById('brandRoot').innerHTML=brandView();return;}document.getElementById('brandRoot').innerHTML='';let html=page==='home'?home():page==='catalog'?catalog():page==='cart'?cartView():page==='checkout'?checkout():page==='saved'?(saved.length?`<h1>Избранное</h1><div class="grid" style="margin-top:25px">${PRODUCTS.filter(p=>saved.includes(p.id)).map(card).join('')}</div>`:empty('heart','Сохраните самое любимое','Нажмите на сердечко рядом с изделием.')):page==='success'?`<div class="empty">${svg('check')}<div class="eyebrow">${lastOrder?.number||'DEMO'}</div><h2>Всё получилось</h2><p>Вы прошли путь покупки. Это демонстрация: заказ не отправлен, оплата не списана.</p><button class="primary" onclick="navigate('profile')">Посмотреть заказ</button><button class="textlink" style="display:block;margin:20px auto" onclick="navigate('catalog')">Вернуться в каталог</button></div>`:profile();document.getElementById('main').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page||(page==='checkout'&&b.dataset.nav==='cart')));paintIcons();updateCount()}
function showModal(html){returnFocus=document.activeElement;document.getElementById('modalContent').innerHTML=html;document.getElementById('overlay').hidden=false;document.body.style.overflow='hidden';document.querySelector('.close').focus()}
function closeModal(){if(!document.getElementById('overlay'))return;document.getElementById('overlay').hidden=true;document.body.style.overflow='';if(returnFocus?.isConnected)returnFocus.focus();returnFocus=null}
function detail(id){let p=pfind(id);showModal(`<div class="detail"><img class="detail-image" src="${p.img}" alt="${p.type} ${p.name}"><div class="detail-copy"><div class="eyebrow">${p.type}</div><h2>${p.name}</h2><div class="price">${Number.isFinite(p.price)?money(p.price)+' <small>сум</small>':'Цена по запросу'}</div><p>${p.description}</p><div class="specs"><div><span>Материал</span>${p.material||'Натуральная кожа'}</div><div><span>Цвет на фото</span>${p.color||'На фотографии'}</div><div><span>Производство</span>Узбекистан</div><div><span>Наличие</span>Уточняется</div></div>${Number.isFinite(p.price)?`<button class="primary full" onclick="add('${id}')">Добавить в корзину</button>`:`<a class="primary full" href="${p.source}" target="_blank" rel="noopener">Уточнить в каталоге бренда</a>`}<button class="secondary full" style="margin-top:10px" onclick="navigate('cart')">Перейти в корзину</button><p class="notice">${Number.isFinite(p.price)?'Цена модели из прошлой публикации используется для демонстрации. Актуальную цену и цвет необходимо подтвердить.':'Подтверждённая цена в сумах не найдена. Товар показан для знакомства с коллекцией.'}</p></div></div>`)}
function showSources(){showModal(`<div class="source-list"><div class="eyebrow">КОНЦЕПТ ATLAS CORP</div><h2>О макете и фотографиях</h2><p style="margin:20px 0">Неофициальный демонстрационный макет. Фотографии изделий — из каталогов KANISHKA. Ссылки на оригинальные публикации приведены ниже. Права на изображения принадлежат их владельцам.</p><ul>${PRODUCTS.map(p=>`<li>${p.name}: <a href="${p.source}" target="_blank" rel="noopener">фотография</a>${p.priceSource?` · <a href="${p.priceSource}" target="_blank" rel="noopener">публикация с ценой</a>`:''}</li>`).join('')}<li><a href="https://lmbd.ru/kanishka/7-symka-polymesyats-bulbul-korichnevaya/" target="_blank" rel="noopener">BULBUL · фотография</a></li><li><a href="https://lmbd.ru/kanishka/6-shopper-bolshoi-dvyhtsvetnyi-chopon/" target="_blank" rel="noopener">CHOPON · фотография</a></li></ul><p>О бренде: <a href="https://www.advantour.com/uzbekistan/artisans/manshaev-alexey.htm" target="_blank" rel="noopener">история KANISHKA</a>, <a href="https://lmbd.ru/kanishka/" target="_blank" rel="noopener">описание бренда</a>.</p><p>В основе навигации Mini App — референс X Heart из портфолио ATLAS. Данные корзины и профиля существуют только до перезагрузки страницы.</p></div>`)}
document.addEventListener('keydown',e=>{if(document.getElementById('overlay').hidden)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const focus=[...document.querySelector('.modal').querySelectorAll('button,a,input,select,[tabindex="0"]')].filter(x=>!x.disabled);const first=focus[0],last=focus[focus.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_demo_cart_item',description:'Добавить реальный товар каталога в демонстрационную корзину. Не создаёт заказ.',inputSchema:{type:'object',properties:{productId:{type:'string'}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.productId!=='string'||!pfind(input.productId))throw Error('Неизвестный товар');add(input.productId);return {productId:input.productId,quantity:cart[input.productId],demo:true}}})).catch(()=>{})}catch(e){}}
setMode(mode);
