let brandCategory='Все';
function brandCard(p){return `<article class="b-product"><button onclick="brandDetail('${p.id}')" aria-label="Подробнее об изделии ${p.name}"><div class="b-product-image"><img src="${p.img}" alt="${p.type} ${p.name}" loading="lazy" width="613" height="920"><span>Смотреть изделие</span></div><div class="b-product-caption"><h3>${p.name}</h3><p>${p.type}</p></div></button></article>`}
function brandGrid(){const ps=PRODUCTS.filter(p=>brandCategory==='Все'||p.category===brandCategory);return ps.map(brandCard).join('')}
function selectBrand(c){brandCategory=c;document.getElementById('brandProducts').innerHTML=brandGrid();document.querySelectorAll('[data-brand-cat]').forEach(b=>b.classList.toggle('active',b.dataset.brandCat===c))}
function brandDetail(id){const p=pfind(id);showModal(`<div class="detail brand-detail"><img class="detail-image" src="${p.img}" alt="${p.type} ${p.name}"><div class="detail-copy"><div class="eyebrow">КОЛЛЕКЦИЯ KANISHKA</div><h2>${p.name}</h2><p>${p.type}</p><p>${p.description}</p><div class="specs"><div><span>Материал</span>${p.material||'Натуральная кожа'}</div><div><span>Категория</span>${p.category}</div></div><a class="primary full" href="${p.source}" target="_blank" rel="noopener">Посмотреть в каталоге бренда</a><button class="secondary full" style="margin-top:12px" onclick="closeModal();goBrand('stores')">Найти магазин</button><p class="notice">Цвета и наличие уточняйте в магазинах KANISHKA.</p></div></div>`)}
function goBrand(id){document.getElementById('brandMenu').classList.remove('open');document.getElementById('brandMenuToggle').setAttribute('aria-expanded','false');document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
function toggleBrandMenu(){const open=document.getElementById('brandMenu').classList.toggle('open');document.getElementById('brandMenuToggle').setAttribute('aria-expanded',open)}
function brandView(){return `<header class="b-header"><a class="b-logo" href="#brandTop" onclick="goBrand('brandTop');return false">KANISHKA<span>ТАШКЕНТ · УЗБЕКИСТАН</span></a><nav id="brandMenu"><a href="#collections" onclick="goBrand('collections');return false">Коллекции</a><a href="#story" onclick="goBrand('story');return false">О бренде</a><a href="#materials" onclick="goBrand('materials');return false">Материалы</a><a href="#stores" onclick="goBrand('stores');return false">Магазины</a></nav><button id="brandMenuToggle" class="b-menu-button" aria-label="Меню сайта" aria-expanded="false" onclick="toggleBrandMenu()"><span></span><span></span></button><a class="b-header-contact" href="https://www.instagram.com/kanishka_dsgn/" target="_blank" rel="noopener">Instagram</a></header>
<section class="b-hero" id="brandTop"><div class="b-hero-image"><img src="assets/chopon.jpg" alt="Шоппер KANISHKA в городском образе" fetchpriority="high"></div><div class="b-hero-shade"></div><div class="b-hero-content"><p class="b-overline">АВТОРСКИЕ ИЗДЕЛИЯ ИЗ УЗБЕКИСТАНА</p><h1>Характер<br>в каждой<br><em>детали.</em></h1><div class="b-hero-bottom"><p>Кожа. Текстиль. Ручная работа.<br>Вещи, с которыми живут.</p><a href="#collections" class="b-outline" onclick="goBrand('collections');return false">Открыть коллекции</a></div></div><span class="b-hero-index">01 / KANISHKA</span></section>
<div class="b-statement"><p>СОЗДАНО В ТАШКЕНТЕ</p><h2>Современная форма.<br><span>Узбекский характер.</span></h2><div><p>KANISHKA соединяет повседневные вещи с культурой места, в котором они созданы. Натуральные материалы, узнаваемые детали и небольшие серии.</p><a href="#story" class="b-link" onclick="goBrand('story');return false">Познакомиться с брендом</a></div></div>
<section class="b-section b-collections" id="collections"><div class="b-section-heading"><div><p class="b-overline">01 / КОЛЛЕКЦИИ</p><h2>Для ваших историй</h2></div><p>Для города, путешествий<br>и маленьких ежедневных ритуалов.</p></div><div class="b-category-grid"><button class="b-category" onclick="selectBrand('Сумки');goBrand('pieces')"><img src="assets/bulbul.jpg" alt="Кожаные сумки KANISHKA" loading="lazy"><div><small>01</small><h3>Сумки</h3><span>Форма на каждый день</span></div></button><button class="b-category" onclick="selectBrand('Аксессуары');goBrand('pieces')"><img src="assets/kulok.jpg" alt="Кожаные аксессуары KANISHKA" loading="lazy"><div><small>02</small><h3>Аксессуары</h3><span>Детали, которые остаются с вами</span></div></button><button class="b-category" onclick="selectBrand('В дорогу');goBrand('pieces')"><img src="assets/sayohat.jpg" alt="Дорожная сумка KANISHKA" loading="lazy"><div><small>03</small><h3>В дорогу</h3><span>Больше пространства для планов</span></div></button></div></section>
<section class="b-section b-pieces" id="pieces"><div class="b-section-heading"><div><p class="b-overline">02 / ИЗДЕЛИЯ</p><h2>Коллекция в деталях</h2></div><span class="b-count">${PRODUCTS.length} изделий</span></div><div class="b-filter" role="group" aria-label="Категории изделий">${['Все',...new Set(PRODUCTS.map(p=>p.category))].map(c=>`<button data-brand-cat="${c}" class="${brandCategory===c?'active':''}" onclick="selectBrand('${c}')">${c}</button>`).join('')}</div><div class="b-product-grid" id="brandProducts">${brandGrid()}</div></section>
<section class="b-story" id="story"><div class="b-story-copy"><p class="b-overline">03 / О БРЕНДЕ</p><h2>Из Ташкента.<br><em>С характером.</em></h2><p>KANISHKA — авторский проект дизайнера Алексея Маньшаева. Первый магазин бренда открылся в Ташкенте в 2011 году.</p><p>В основе коллекций — натуральная кожа, текстиль и интерес к узбекской культуре. Орнаменты и знакомые формы получают новое прочтение в вещах для современной жизни.</p><div class="b-principles"><span>Функциональность</span><span>Лаконичность</span><span>Индивидуальность</span></div></div><div class="b-story-photo"><img src="assets/shanba.jpg" alt="Авторская сумка KANISHKA SHANBA" loading="lazy"><span>МАЛЫЕ СЕРИИ. ВНИМАНИЕ К ДЕТАЛЯМ.</span></div></section>
<section class="b-section b-materials" id="materials"><div class="b-section-heading"><div><p class="b-overline">04 / МАТЕРИАЛЫ И ПОДХОД</p><h2>Красота, которую<br>можно почувствовать</h2></div></div><div class="b-material-grid"><article><span>01</span><h3>Натуральная кожа</h3><p>Фактура, пластичность и выразительный цвет. Материал задаёт настроение каждой сумке и каждому аксессуару.</p></article><article><span>02</span><h3>Ручная работа</h3><p>Мелкосерийное производство и внимание к тому, что замечаешь вблизи: строчке, силуэту, рисунку и деталям.</p></article><article><span>03</span><h3>Культурный контекст</h3><p>Узбекские мотивы вписаны в современную повседневность. Наследие становится частью личного стиля.</p></article></div></section>
<section class="b-editorial"><img src="assets/navruz.jpg" alt="Красная кожаная сумка NAVRUZ" loading="lazy"><div><p class="b-overline">ЦВЕТ КАК АКЦЕНТ</p><h2>Иногда<br>всё решает<br><em>одна деталь.</em></h2><p>Знакомый образ. Другое настроение.</p><button class="b-outline" onclick="brandDetail('navruz')">Рассмотреть NAVRUZ</button></div></section>
<section class="b-section b-stores" id="stores"><div class="b-section-heading"><div><p class="b-overline">05 / МАГАЗИНЫ</p><h2>Познакомимся<br>в Ташкенте</h2></div><p>Рассмотрите фактуру, примерьте изделие<br>и найдите то, что подходит именно вам.</p></div><div class="b-store-grid">${[{n:'Шота Руставели',a:'ул. Шота Руставели, 39',p:'+998 71 255 03 93',t:'+998712550393'},{n:'Афросиаб',a:'ул. Афросиаб, 39',p:'+998 71 252 57 77',t:'+998712525777'},{n:'Оккурган',a:'ул. Оккурган, 21',p:'+998 71 268 95 19',t:'+998712689519'}].map((s,i)=>`<article><span>0${i+1} / ТАШКЕНТ</span><h3>${s.n}</h3><p>${s.a}</p><a class="b-phone" href="tel:${s.t}">${s.p}</a><a class="b-link" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('KANISHKA '+s.a+' Ташкент')}" target="_blank" rel="noopener">Открыть на карте</a></article>`).join('')}</div><p class="b-hours">Перед визитом уточните часы работы по телефону магазина.</p></section>
<section class="b-follow"><p class="b-overline">ПРОДОЛЖИМ ЗНАКОМСТВО</p><h2>Новые изделия.<br>Новые истории.</h2><div><a href="https://www.instagram.com/kanishka_dsgn/" target="_blank" rel="noopener">Instagram / kanishka_dsgn</a><a href="https://t.me/kanishka_dsgn" target="_blank" rel="noopener">Telegram / kanishka_dsgn</a></div></section>
<footer class="b-footer"><div class="b-footer-wordmark">KANISHKA</div><div class="b-footer-bottom"><span>ТАШКЕНТ, УЗБЕКИСТАН</span><button onclick="setMode('mini')">Открыть Mini App</button><button onclick="showSources()">О концепте и источниках</button><span>КОНЦЕПТ ATLAS CORP · 2026</span></div></footer>`}
