window.PRODUCTS=[
  {
    "id": "shanba",
    "name": "SHANBA",
    "type": "Сумка-трансформер",
    "category": "Сумки",
    "color": "Красный",
    "description": "Компактная сумка для ежедневных маршрутов. Носите на поясе или через плечо.",
    "price": 540000,
    "img": "assets/shanba.jpg",
    "source": "https://lmbd.ru/kanishka/9-symka-transformer-shanba-krasnogo-tsveta/",
    "priceSource": "https://t.me/kanishka_dsgn/6600"
  },
  {
    "id": "navruz",
    "name": "NAVRUZ",
    "type": "Сумка через плечо",
    "category": "Сумки",
    "color": "Красный",
    "description": "Лаконичная форма и выразительная фактура натуральной кожи.",
    "price": 540000,
    "img": "assets/navruz.jpg",
    "source": "https://lmbd.ru/kanishka/5-symka-navruz-krasnyi/",
    "priceSource": "https://t.me/kanishka_dsgn/6743"
  },
  {
    "id": "sayohat",
    "name": "SAYOHAT",
    "type": "Дорожная сумка",
    "category": "В дорогу",
    "color": "Чёрный",
    "description": "Вместительная сумка для поездок и выходных за городом.",
    "price": 1600000,
    "img": "assets/sayohat.jpg",
    "source": "https://lmbd.ru/kanishka/2-dorozhnaya-symka-sayohat/",
    "priceSource": "https://t.me/kanishka_dsgn/6583"
  },
  {
    "id": "kulok",
    "name": "KULOK",
    "type": "Чехол для наушников",
    "category": "Аксессуары",
    "color": "Коричневый",
    "description": "Небольшой кожаный аксессуар с декоративным орнаментом.",
    "price": 125000,
    "img": "assets/kulok.jpg",
    "source": "https://lmbd.ru/kanishka/4-chehol-dlya-nayshnikov-melochnitsa-kulok/",
    "priceSource": "https://t.me/kanishka_dsgn/6599"
  },
  {
    "id": "kema",
    "name": "KEMA",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/kema.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-885726289343-kema-oranzhevaya",
    "description": "Размер 27x14 cm Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "dumba",
    "name": "DUMBA",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/dumba.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-804810887152-sumka-dumba-kofe",
    "description": "Размер 32х21х6 см Состав: натуральная кожа  ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "liqildoq",
    "name": "LIQILDOQ",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/liqildoq.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-803221660291-liqildoq",
    "description": "Размер 19*13 см Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "tadbirkor",
    "name": "TADBIRKOR",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/tadbirkor.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-523212038751-sumka-portfel-tadbirkor",
    "description": "Размер 30х42 см Состав: натуральная кожа  ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "tabassum",
    "name": "TABASSUM",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/tabassum.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-754323119772-sumka-tabassum-print-girih",
    "description": "Размер 36*16 см Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "bonka",
    "name": "BONKA",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/bonka.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-406493144932-bonka",
    "description": "Размер 27x14 cm Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "jiddiy",
    "name": "JIDDIY",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/jiddiy.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-668804873772-sumka-jiddiy-korichnevaya",
    "description": "Размер 32х21х6 см Состав: натуральная кожа  ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "marhabo",
    "name": "MARHABO",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/marhabo.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-365240743522-marhabo-vostok",
    "description": "Размер 18x15x8 cm Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "oypopuk",
    "name": "OYPOPUK",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/oypopuk.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-133754334762-oypopuk-korichnevaya",
    "description": "Размер 21x15 cm Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "akilvoi",
    "name": "AKILVOI",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/akilvoi.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-153387412432-sumka-portfel-akilvoi",
    "description": "Размер 30х42 см Состав: натуральная кожа  ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "jilov",
    "name": "JILOV",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/jilov.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-500002974142-sumka-jilov-vostok",
    "description": "Размер: 24*18см Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "paket",
    "name": "PAKET",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/paket.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-488010073882-shopper-paket-shokolad",
    "description": "Размер: 44x44 см Состав: натуральная кожа",
    "price": 530000,
    "priceSource": "https://t.me/kanishka_dsgn/10371",
    "color": "На фотографии"
  },
  {
    "id": "bino",
    "name": "BINO",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/bino.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-337173599492-bino",
    "description": "Размер: 47x44 см Состав: холщовая ткань + натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "halta",
    "name": "HALTA",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/halta.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-872120855992-halta-rizhaya",
    "description": "Размер 18.5х15 Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "ulkan",
    "name": "ULKAN",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/ulkan.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-235559757282-ulkan-camel",
    "description": "Размер: 27*25см Состав: натуральная кожа",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "kamtar",
    "name": "KAMTAR",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/kamtar.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-610190903302-shopper-kamtar",
    "description": "Размер: 42x35 см Состав: натуральная кожа",
    "price": 510000,
    "priceSource": "https://t.me/s/kanishka_dsgn?before=8039",
    "color": "На фотографии"
  },
  {
    "id": "baton",
    "name": "BATON",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/baton.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-458916173492-baton-korichnevii",
    "description": "Размер: 32*17см Состав: натуральная кожа ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "oy",
    "name": "OY",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/oy.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-370495294843-sumka-oy-seraya",
    "description": "Размер: 44x70 см Состав: натуральная телячья кожа ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "sandik",
    "name": "SANDIK",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/sandik.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-224679846602-sandik-print-arabeska-i-tisnenie",
    "description": "Размер: 15*19.5 см Состав: натуральная кожа ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "sir",
    "name": "SIR",
    "type": "Сумка",
    "category": "Сумки",
    "img": "assets/sir.jpg",
    "source": "https://kanishkaspb.ru/bags/tproduct/748211388-216920294413-sir-gorkii-shokolad",
    "description": "Размер: 27*39 см Состав: натуральная кожа ",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "bulbul",
    "name": "BULBUL",
    "type": "Сумка-полумесяц",
    "category": "Сумки",
    "img": "assets/bulbul.jpg",
    "source": "https://lmbd.ru/kanishka/7-symka-polymesyats-bulbul-korichnevaya/",
    "description": "Сумка-полумесяц KANISHKA из натуральной кожи.",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "chopon",
    "name": "CHOPON",
    "type": "Шоппер",
    "category": "Сумки",
    "img": "assets/chopon.jpg",
    "source": "https://lmbd.ru/kanishka/6-shopper-bolshoi-dvyhtsvetnyi-chopon/",
    "description": "Шоппер KANISHKA из натуральной кожи.",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  },
  {
    "id": "laptop",
    "name": "LAPTOP 13–14",
    "type": "Чехол для ноутбука",
    "category": "Аксессуары",
    "img": "assets/laptop.jpg",
    "source": "https://lmbd.ru/kanishka/3-chehol-dlya-noytbyka-13-14/",
    "description": "Чехол для ноутбука KANISHKA из натуральной кожи.",
    "price": null,
    "priceSource": null,
    "color": "На фотографии"
  }
];